spring:
  application:
    name: zuul-sentinel-template
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8720
      # sentinel是懒加载机制，只有访问过一次的资源才会被监控
      # 取消控制台懒加载，项目启动即连接Sentinel
      eager: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8082

zuul:
  routes:
#    # 方式1
#    a-server:
#      path: /rule/*
#      service-id: rule-liteflow
#    # 方式2
#    rule-liteflow:
#      path: /rule/*
    # 方式3
    rule-liteflow: /rule/**

sm:
  sm4key: x/JXskhWPfYyZ2nMbEOmrw==
  sm2key-private: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgh8tf2S0bMHgiwd44rWOBqT6PgdVtnaVYYP7K0H8RNWmgCgYIKoEcz1UBgi2hRANCAAQIOtyLKft0zdIF8aPjDqAZbCx67an5i0dhQ1XKU9wrZouP+uS94PjI/Ae8z0WKxlkPx0ufOYmIgsWWCx4Gf0sH
  sm2key-public: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAECDrciyn7dM3SBfGj4w6gGWwseu2p+YtHYUNVylPcK2aLj/rkveD4yPwHvM9FisZZD8dLnzmJiILFlgseBn9LBw==